version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  web:
    build: .
    command: bin/dev
    volumes:
      - .:/wakannyai
    ports:
      - "3000:3000"
    shm_size: "2gb"
    depends_on:
      - db
  test:
    build: .
    depends_on: [db]
    volumes:
      - .:/wakannyai
    environment:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:postgres@db:5432/wakannyai_test
    entrypoint: ""
    command: bash -lc "bin/rails tailwindcss:build && bundle exec rails db:test:prepare && bundle exec rspec"
    shm_size: "2gb"