name: RSpec

on:
  push:
  pull_request:

concurrency:
  group: rspec-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rspec:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: my_blog_app_test
        ports:
          - "5432:5432"
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/my_blog_app_test
      # RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }} # 必要な場合のみ

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
          bundler-cache: true

      - uses: browser-actions/setup-chrome@v1

      - name: Install system deps
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libvips

      - name: DB prepare
        run: bin/rails db:prepare

      # ★ Tailwind（tailwindcss-rails）でCSS生成
      - name: Build Tailwind
        run: bin/rails tailwindcss:build

      # （オプション）Sprocketsにマニフェストを作らせたい場合は残す
      - name: Precompile assets for test
        env:
          RAILS_ENV: test
          SECRET_KEY_BASE_DUMMY: "1"
        run: bin/rails assets:precompile

      - name: Run RSpec
        run: bundle exec rspec --format documentation
